databases:
  - name: restauranteitalianodb
    plan: free
    databaseName: restaurante
    user: mysite

services:
  - type: web
    plan: free
    name: restaurante_italiano_web
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn restaurante_italiano.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restauranteitalianodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4